# Generated by Django 2.2.5 on 2019-09-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0002_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
    ]
